fix(provider): authorization action gives 404 for route not found, added required test case
sourcefuse/loopback4-authorization pull request #36
Opened 2022-02-08 17:40 UTC by rohitvishwakarma-sf

GH-35

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-19 03:29 UTC, samarpan-b requested changes

2022-04-19 03:29 UTC, samarpan-b commented on src/__tests__/unit/authorization-action.provider.unit.ts
> +  it('should throw 404 if non existing route is hitted', async () => {
```suggestion
  it('should throw 404 if non existing route is hit', async () => {
```

2022-04-19 03:29 UTC, samarpan-b commented on src/providers/authorization-action.provider.ts
> +      throw new HttpErrors.NotFound();
```suggestion
      throw new HttpErrors.NotFound("API not found !");
```

2022-05-09 07:02 UTC, akshatdubeysf approved these changes

2022-05-09 07:03 UTC, merged

2022-05-25 10:51 UTC, yeshamavani commented
:tada: This PR is included in version 5.0.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/loopback4-authorization/v/5.0.4)
- [GitHub release](https://github.com/sourcefuse/loopback4-authorization/releases/tag/v5.0.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: